# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb128f546eb237a9517009983d10d47ea18d955e7531134595819924ce4cb4b72f37c3a6541dbd1d24849badbde221e747436edae9b87b1dee2b20ee90116d02

test:
  secret_key_base: c37382a695b182738484d514e94fd8b534bd4eddaf9ff1117e8f3b1d1bac7ef50250313d5c3c2e8f4240f066dad0d34edaf516e3fa47c3b50d1ee298408e61b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
